/**
 * Generate public/sitemap.xml for the real domain.
 *
 * The route list is static, so the only thing that needs to change between
 * deployments is the origin — and a hand-edited sitemap with the wrong domain in it
 * is worse than none. Run: SITE_URL=https://ksochd.org npm run sitemap
 */
import { writeFileSync } from 'node:fs'

const ROUTES = [
  ['/', '1.0'],
  ['/about', '0.8'],
  ['/programs', '0.9'],
  ['/impact', '0.8'],
  ['/events', '0.7'],
  ['/gallery', '0.6'],
  ['/stories', '0.7'],
  ['/volunteer', '0.9'],
  ['/donate', '0.9'],
  ['/contact', '0.8'],
  // /admin is deliberately absent — it is not public and should never be indexed.
]

const url = process.env.SITE_URL || process.argv[2]
if (!url || !/^https?:\/\//.test(String(url))) {
  console.error('Usage: SITE_URL=https://your-domain.org npm run sitemap')
  process.exit(1)
}
const origin = String(url).replace(/\/$/, '')
const today = new Date().toISOString().slice(0, 10)

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/make-sitemap.mjs on ${today}. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTES.map(([path, priority]) => `  <url>
    <loc>${origin}${path}</loc>
    <lastmod>${today}</lastmod>
    <priority>${priority}</priority>
  </url>`).join('\n')}
</urlset>
`

writeFileSync(new URL('../public/sitemap.xml', import.meta.url), xml)
console.log(`sitemap.xml written for ${origin} (${ROUTES.length} routes)`)
